#!/usr/bin/env python3
################################################################################
# Copyright (c) 2024 STMicroelectronics.
# All rights reserved. This program and the accompanying materials
# is the property of STMicroelectronics and must not be
# reproduced, disclosed to any third party, or used in any
# unauthorized manner without written consent.
################################################################################

import os
import sys
import subprocess

if __name__ == "__main__":
	args = ["java", "-Xdock:icon="+os.path.abspath(os.path.join(os.path.dirname(__file__) , "../Resources/STLinkUpgradeIcon.icns")), "-jar", os.path.abspath(os.path.join(os.path.dirname(__file__) , "../Resources/app/STLinkUpgrade.jar"))]
	sys.exit(subprocess.run(args).returncode)
