from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
import sys

def keygen(private_path: str, public_c_path: str):
    # generate keypair on curve P-256 — matches uECC_curve_secp256r1()
    key = ec.generate_private_key(ec.SECP256R1())

    # save private key as PEM for signing
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption()
    )
    open(private_path, "wb").write(pem)
    print(f"Private key → {private_path}")

    # extract raw public key bytes (64 bytes: 32 x + 32 y, uncompressed minus 0x04 prefix)
    pub = key.public_key()
    pub_bytes = pub.public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint
    )[1:]  # strip 0x04 uncompressed prefix — micro-ecc wants raw 64 bytes

    # write as C header
    c_array = ", ".join(f"0x{b:02X}" for b in pub_bytes)
    header = f"""#ifndef PUBLIC_KEY_H
#define PUBLIC_KEY_H
#include <stdint.h>
// ECDSA P-256 public key — 64 bytes (32 x + 32 y)
// Generated by keygen.py — do not edit manually!
static const uint8_t ECDSA_PUBLIC_KEY[64] = {{
    {c_array}
}};
#endif
"""
    open(public_c_path, "w").write(header)
    print(f"Public key header → {public_c_path}")

if __name__ == "__main__":
    keygen("private_key.pem", "../BL_HW_AGN/middleware/crypto/public_key.h")